import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/app/components/Navbar/navbar'
import Footer from '@/app/components/Footer/footer'

const lightMode = 'dark'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MDWiki',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja" className=''>
      <body className={inter.className}>
        <main className={`flex h-screen w-screen flex-col text-sm text-white dark:text-white ${lightMode}`}>
          <div className='h-16'>
            <Navbar />
          </div>
          <div id="child" className="flex w-full h-full">
            {children}
          </div>
          <div className='h-8 bottom-0'>
            <Footer />
          </div>
        </main>
      </body>
    </html>
  )
}
